language: csharp

# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: SharpBCI
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/berkona/SharpBCI.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

install:
  - nuget restore SharpBCI.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  
# Build your code and run unit tests
script:
  - xbuild /p:Configuration=Release SharpBCI.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SharpBCI.Tests/bin/Release/SharpBCI.Tests.dll

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
