var namespace_sharp_b_c_i =
[
    [ "IPredictor< T >", "interface_sharp_b_c_i_1_1_i_predictor_3_01_t_01_4.html", "interface_sharp_b_c_i_1_1_i_predictor_3_01_t_01_4" ],
    [ "IPredictorPipeable", "interface_sharp_b_c_i_1_1_i_predictor_pipeable.html", "interface_sharp_b_c_i_1_1_i_predictor_pipeable" ],
    [ "AggregatePredictionPipeable", "class_sharp_b_c_i_1_1_aggregate_prediction_pipeable.html", "class_sharp_b_c_i_1_1_aggregate_prediction_pipeable" ],
    [ "Predictor", "class_sharp_b_c_i_1_1_predictor.html", "class_sharp_b_c_i_1_1_predictor" ],
    [ "AggregateKNNCorrelationPredictor", "class_sharp_b_c_i_1_1_aggregate_k_n_n_correlation_predictor.html", "class_sharp_b_c_i_1_1_aggregate_k_n_n_correlation_predictor" ],
    [ "AggregateKNNDTWPredictor", "class_sharp_b_c_i_1_1_aggregate_k_n_n_d_t_w_predictor.html", "class_sharp_b_c_i_1_1_aggregate_k_n_n_d_t_w_predictor" ],
    [ "TournamentArtifactPipeable", "class_sharp_b_c_i_1_1_tournament_artifact_pipeable.html", "class_sharp_b_c_i_1_1_tournament_artifact_pipeable" ],
    [ "IArtifactDetector", "interface_sharp_b_c_i_1_1_i_artifact_detector.html", "interface_sharp_b_c_i_1_1_i_artifact_detector" ],
    [ "ARArtifactDetector", "class_sharp_b_c_i_1_1_a_r_artifact_detector.html", "class_sharp_b_c_i_1_1_a_r_artifact_detector" ],
    [ "TournamentArtifactDectector", "class_sharp_b_c_i_1_1_tournament_artifact_dectector.html", "class_sharp_b_c_i_1_1_tournament_artifact_dectector" ],
    [ "AsyncStreamReader", "class_sharp_b_c_i_1_1_async_stream_reader.html", "class_sharp_b_c_i_1_1_async_stream_reader" ],
    [ "AsyncStreamWriter", "class_sharp_b_c_i_1_1_async_stream_writer.html", "class_sharp_b_c_i_1_1_async_stream_writer" ],
    [ "EEGDeviceAdapter", "class_sharp_b_c_i_1_1_e_e_g_device_adapter.html", "class_sharp_b_c_i_1_1_e_e_g_device_adapter" ],
    [ "RemoteOSCAdapter", "class_sharp_b_c_i_1_1_remote_o_s_c_adapter.html", "class_sharp_b_c_i_1_1_remote_o_s_c_adapter" ],
    [ "DummyAdapterSignal", "struct_sharp_b_c_i_1_1_dummy_adapter_signal.html", "struct_sharp_b_c_i_1_1_dummy_adapter_signal" ],
    [ "InstrumentedDummyAdapter", "class_sharp_b_c_i_1_1_instrumented_dummy_adapter.html", "class_sharp_b_c_i_1_1_instrumented_dummy_adapter" ],
    [ "CSVReadAdapter", "class_sharp_b_c_i_1_1_c_s_v_read_adapter.html", "class_sharp_b_c_i_1_1_c_s_v_read_adapter" ],
    [ "DummyAdapter", "class_sharp_b_c_i_1_1_dummy_adapter.html", "class_sharp_b_c_i_1_1_dummy_adapter" ],
    [ "DynamicTimeWarping", "class_sharp_b_c_i_1_1_dynamic_time_warping.html", "class_sharp_b_c_i_1_1_dynamic_time_warping" ],
    [ "SeriesVariable", "class_sharp_b_c_i_1_1_series_variable.html", "class_sharp_b_c_i_1_1_series_variable" ],
    [ "EEGEvent", "class_sharp_b_c_i_1_1_e_e_g_event.html", "class_sharp_b_c_i_1_1_e_e_g_event" ],
    [ "IVectorizedSmoother< T >", "interface_sharp_b_c_i_1_1_i_vectorized_smoother_3_01_t_01_4.html", "interface_sharp_b_c_i_1_1_i_vectorized_smoother_3_01_t_01_4" ],
    [ "ExponentialVectorizedSmoother", "class_sharp_b_c_i_1_1_exponential_vectorized_smoother.html", "class_sharp_b_c_i_1_1_exponential_vectorized_smoother" ],
    [ "XCorrVectorizedSmoother", "class_sharp_b_c_i_1_1_x_corr_vectorized_smoother.html", "class_sharp_b_c_i_1_1_x_corr_vectorized_smoother" ],
    [ "FFTPipeable", "class_sharp_b_c_i_1_1_f_f_t_pipeable.html", "class_sharp_b_c_i_1_1_f_f_t_pipeable" ],
    [ "BandpassPipeable", "class_sharp_b_c_i_1_1_bandpass_pipeable.html", "class_sharp_b_c_i_1_1_bandpass_pipeable" ],
    [ "SimpleFilterPipeable", "class_sharp_b_c_i_1_1_simple_filter_pipeable.html", "class_sharp_b_c_i_1_1_simple_filter_pipeable" ],
    [ "IFilter< T >", "interface_sharp_b_c_i_1_1_i_filter_3_01_t_01_4.html", "interface_sharp_b_c_i_1_1_i_filter_3_01_t_01_4" ],
    [ "MultiFilter< T >", "class_sharp_b_c_i_1_1_multi_filter_3_01_t_01_4.html", "class_sharp_b_c_i_1_1_multi_filter_3_01_t_01_4" ],
    [ "MovingAverageFilter", "class_sharp_b_c_i_1_1_moving_average_filter.html", "class_sharp_b_c_i_1_1_moving_average_filter" ],
    [ "ExponentialFilter", "class_sharp_b_c_i_1_1_exponential_filter.html", "class_sharp_b_c_i_1_1_exponential_filter" ],
    [ "RecursiveFilter", "class_sharp_b_c_i_1_1_recursive_filter.html", "class_sharp_b_c_i_1_1_recursive_filter" ],
    [ "NarrowPassFilter", "class_sharp_b_c_i_1_1_narrow_pass_filter.html", "class_sharp_b_c_i_1_1_narrow_pass_filter" ],
    [ "NotchFilter", "class_sharp_b_c_i_1_1_notch_filter.html", "class_sharp_b_c_i_1_1_notch_filter" ],
    [ "ConvolvingFilter", "class_sharp_b_c_i_1_1_convolving_filter.html", "class_sharp_b_c_i_1_1_convolving_filter" ],
    [ "ConvolvingSingleEndedFilter", "class_sharp_b_c_i_1_1_convolving_single_ended_filter.html", "class_sharp_b_c_i_1_1_convolving_single_ended_filter" ],
    [ "ConvolvingDoubleEndedFilter", "class_sharp_b_c_i_1_1_convolving_double_ended_filter.html", "class_sharp_b_c_i_1_1_convolving_double_ended_filter" ],
    [ "IndexableQueue< T >", "class_sharp_b_c_i_1_1_indexable_queue_3_01_t_01_4.html", "class_sharp_b_c_i_1_1_indexable_queue_3_01_t_01_4" ],
    [ "ILogOutput", "interface_sharp_b_c_i_1_1_i_log_output.html", "interface_sharp_b_c_i_1_1_i_log_output" ],
    [ "ConsoleLogger", "class_sharp_b_c_i_1_1_console_logger.html", "class_sharp_b_c_i_1_1_console_logger" ],
    [ "FileLogger", "class_sharp_b_c_i_1_1_file_logger.html", "class_sharp_b_c_i_1_1_file_logger" ],
    [ "IPipeable", "interface_sharp_b_c_i_1_1_i_pipeable.html", "interface_sharp_b_c_i_1_1_i_pipeable" ],
    [ "Pipeable", "class_sharp_b_c_i_1_1_pipeable.html", "class_sharp_b_c_i_1_1_pipeable" ],
    [ "SerializedPipeline", "class_sharp_b_c_i_1_1_serialized_pipeline.html", "class_sharp_b_c_i_1_1_serialized_pipeline" ],
    [ "SerializedStage", "class_sharp_b_c_i_1_1_serialized_stage.html", "class_sharp_b_c_i_1_1_serialized_stage" ],
    [ "SerializedConnectionInfo", "class_sharp_b_c_i_1_1_serialized_connection_info.html", "class_sharp_b_c_i_1_1_serialized_connection_info" ],
    [ "IPreprocessor", "interface_sharp_b_c_i_1_1_i_preprocessor.html", "interface_sharp_b_c_i_1_1_i_preprocessor" ],
    [ "Preprocessors", "class_sharp_b_c_i_1_1_preprocessors.html", [
      [ "NonePreprocessor", "class_sharp_b_c_i_1_1_preprocessors_1_1_none_preprocessor.html", "class_sharp_b_c_i_1_1_preprocessors_1_1_none_preprocessor" ],
      [ "NormalizationPreprocessor", "class_sharp_b_c_i_1_1_preprocessors_1_1_normalization_preprocessor.html", "class_sharp_b_c_i_1_1_preprocessors_1_1_normalization_preprocessor" ]
    ] ],
    [ "StandardizationPreprocessor", "class_sharp_b_c_i_1_1_standardization_preprocessor.html", "class_sharp_b_c_i_1_1_standardization_preprocessor" ],
    [ "CentralizationPreprocessor", "class_sharp_b_c_i_1_1_centralization_preprocessor.html", "class_sharp_b_c_i_1_1_centralization_preprocessor" ],
    [ "SharpBCIConfig", "class_sharp_b_c_i_1_1_sharp_b_c_i_config.html", "class_sharp_b_c_i_1_1_sharp_b_c_i_config" ],
    [ "SharpBCIBuilder", "class_sharp_b_c_i_1_1_sharp_b_c_i_builder.html", "class_sharp_b_c_i_1_1_sharp_b_c_i_builder" ],
    [ "TrainedEvent", "class_sharp_b_c_i_1_1_trained_event.html", "class_sharp_b_c_i_1_1_trained_event" ],
    [ "SharpBCI", "class_sharp_b_c_i_1_1_sharp_b_c_i.html", "class_sharp_b_c_i_1_1_sharp_b_c_i" ],
    [ "TrainedEventEmitter", "class_sharp_b_c_i_1_1_trained_event_emitter.html", "class_sharp_b_c_i_1_1_trained_event_emitter" ],
    [ "RawEventEmitter", "class_sharp_b_c_i_1_1_raw_event_emitter.html", "class_sharp_b_c_i_1_1_raw_event_emitter" ],
    [ "EEGDeviceProducer", "class_sharp_b_c_i_1_1_e_e_g_device_producer.html", "class_sharp_b_c_i_1_1_e_e_g_device_producer" ],
    [ "OnlineVariance", "class_sharp_b_c_i_1_1_online_variance.html", "class_sharp_b_c_i_1_1_online_variance" ],
    [ "ARModel", "class_sharp_b_c_i_1_1_a_r_model.html", "class_sharp_b_c_i_1_1_a_r_model" ]
];